- name: check the number
  hosts: local
  connection: local
  vars:
   number: 10
  tasks: 
  - name: check the number
    ansible.builtin.debug:
      msg: "check the {{number}} is less than 12"
    when: number < 12  