- name: check the number
  hosts: local
  connection: local
  var_promp:
  - name: number
    promt: please enter the numer
    private: false
  tasks: 
  - name: check the number
    ansible.builtin.debug:
      msg: "check the {{number}} is less than 12"
    when: number < 12  