
- name: install nginx and run
  host: 172.31.81.216
  become: yes
  tasks: 
  - name: install nginx
    ansible.builtin.package:
    name: nginx
    state: present
  - name: run the nginx
    ansible.builtin.service:
    name: nginx

    state: started
    enabled: yes 
